"""empty message

Revision ID: 15103bc91121
Revises: 0f2cea59a2e0
Create Date: 2019-04-02 19:59:25.962777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15103bc91121'
down_revision = '0f2cea59a2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highlight_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highlight_post')
    # ### end Alembic commands ###
